server {
    listen 80;
    server_name crm.kodan.software crm.kodan.local;

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        root /usr/share/nginx/html/crm;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name tracker.kodan.software tracker.kodan.local;

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        root /usr/share/nginx/html/tracker;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name superadmin.kodan.software superadmin.kodan.local;

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        root /usr/share/nginx/html/superadmin;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
